line-length = 100
src = ["."]
target-version = "py311"

[lint]
select = [
    "E", # pycodestyle errors
    "F", # pyflakes
    "I", # isort (import sorting)
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "RUF",# ruff-specific rules
]

exclude = [
    "__init__.py"
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"